### ISSUE TITLE
Beginner tutorial does not run on Ventura 13.1 M1 

### ISSUE THREAD

**Issue by pedro-alonsod** [rstudio/tensorflow.rstudio.com#47]
Hi, 

I am trying my hand at the beginner tutorial after successfully installing TensorFlow on Rstudio but trying the code I get the following error:
Tuto - Beginner.

Error: 

`Traceback (most recent call last):
  File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: Graph execution error:

Detected at node 'StatefulPartitionedCall_2' defined at (most recent call last):
    File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/engine/training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/engine/training.py", line 1027, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 527, in minimize
      self.apply_gradients(grads_and_vars)
    File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1140, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 634, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1166, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1216, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "/Users/pedroalonso/opt/anaconda3/envs/thesis/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1211, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall_2'
could not find registered platform with id: 0x17f5d0f40
	 [[{{node StatefulPartitionedCall_2}}]] [Op:__inference_train_function_2604]`

Any help? Thanks.

**Comment by t-kalinowski** [comment]
Welcome!

I can't reproduce the error on Monterey (macOS 12.6), The [beginner quickstart guide](https://github.com/rstudio/tensorflow.rstudio.com/blob/main/tutorials/quickstart/beginner.qmd) renders without error.

I'll update macOS and see if I can reproduce the issue.

I'm not sure if it's related, but there are a handful of TensorFlow operations that fail on M1 Macs with tensors that are placed on the GPU. The fix (until the appropriate M1 GPU kernel is available), is to pin the operation to the CPU.

e.g., from the "Apple Silicon" section in `?install_tensorflow()`:

> Tensorflow on Apple Silicon is not officially supported by the Tensorflow maintainers. However Apple has published a custom version of Tensorflow compatible with Arm Macs. `install_tensorflow()` will install the special packages tensorflow-macos and tensorflow-metal on Arm Macs. See https://developer.apple.com/metal/tensorflow-plugin/ for instructions on how to do the equivalent manually. Please note that this is an experimental build of both Python and Tensorflow, with known issues. In particular, certain operations will cause errors, but can often be remedied by pinning them to the CPU. For example:
>  ```r
>   x <- array(runif(64*64), c(1, 64, 64))
>   keras::layer_random_rotation(x, .5)  # Error:
>   # No registered 'RngReadAndSkip' OpKernel for 'GPU' devices
>   # Pin the operation to the CPU to avoid the error
>   with(tf$device("CPU"), keras::layer_random_rotation(x, .5) ) # No Error
>   ```

**Comment by pedro-alonsod** [comment]
Hi,

I had the same problem, I think, with python only; the fix I found was to do this:

`model.compile(optimizer=tf.keras.optimizers.legacy.Adam(learning_rate=1e-3), loss=loss_fn, metrics=["accuracy"])`

It may be the same in Rstudio. But I'm not sure how to use the optimizer adam from the legacy in RStudio. 

You could try that and tell me please?

Thanks!

**Comment by t-kalinowski** [comment]
If in python you encounter something like this:
```python
tf.keras.optimizers.legacy.Adam(learning_rate=1e-3)
```
and you want to translate it to R, you can for the most part just replace `.` with `$`
```R
library(tensorflow)
tf$keras$optimizers$legacy$Adam(learning_rate=1e-3)
```
(Note in R, the `tf` symbol comes from the `tensorflow` package.)

**Comment by pedro-alonsod** [comment]
Yes! That did it also for R! Thank you so much! I guess the issues with tensorflow in M1 should be similar to those with the newest packages.

To any one who experience this problem with the newest tensorflow-macos package, here is the link where I got the python fix: https://developer.apple.com/forums/thread/721619

Thanks!
